### PR TITLE
KD - added frontend 'select all' button in quarters dropdown

### PR DESCRIPTION
**Pull request by kdhulipala41**
In this PR I add a "select all" option to the frontend, which appears in the dropdown under the "quarters" field.

### CODE REVIEW

**Review by b4k3s — APPROVED** [review]
LGTM

**Review by cameron-barrett — APPROVED** [review]

**Review by pconrad — CHANGES_REQUESTED** [review]
What is the use case for this?    

There is not backend support for this, and changing the dropdown in this way seems like it would just cause the app to crash.

What user story is this connected to?

Also: frontend changes should have before/after live storybook links to test the component.

Before we even talk about what changes you'd make, I need to understand where this change to the component is leading; what do you anticipate that it would enable if this were in place?

Look at the places where the basic course search form is used in the app, and ask whether this makes sense.  If it does, then help me understand how this will play out.

**Comment by pconrad** [comment]
So this actually breaks the app, because there is no support in the api this page is built on for asking for data for multiple quarters.  You get this:

image

So this isn't mergeable, because it modifies an existing component in way that breaks the app.

Try doing a basic search with "All Quarters" selected, and you'll see that you get an error message.

**Comment by pconrad** [comment]
Closing per @kdhulipala41

**Pull request closed without merging**
