### PR TITLE
bc - added menu option for search by instructor

### PR DESCRIPTION
**Pull request by BenCrutt**
This PR updates the NavBar.
It changes the course description dropdown into just a single link to the course description search. 
It removes the dropdown for course history, and instead adds a new dropdown called search by which contains two links, one to lead to course history search and one that leads to course instructor search.
Form for course instructor search coming later.

StoryBook:
[Before](https://ucsb-cs156-s23.github.io/proj-courses-s23-7pm-1/storybook/?path=/docs/components-nav-appnavbar--basic-not-logged-in)
[After](https://ucsb-cs156-s23.github.io/proj-courses-s23-7pm-1/prs/29/storybook/?path=/docs/components-nav-appnavbar--basic-not-logged-in)

Screenshots:

Before:
Screenshot 2023-05-29 at 11 36 43 PM

After:
Screenshot 2023-05-31 at 7 50 52 PM

### CODE REVIEW

**Review by b4k3s — COMMENTED** [review]
LGTM

**Review by b4k3s — DISMISSED** [review]
LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
Typically, when we add a menu item, we like to see it go to at least a "placeholder page" that says "feature coming soon", or something like that, rather than just the "blank page" that represents an error condition.

A better strategy (often used in industry) is to make the page first, and while it's not in development, NOT have a link to it from a menu until the page is completely implemented.  That way, developers can get to it (by manually typing in the url to the url bar in the browser) but real users don't end up there until the page is fully implemented.

Could I ask you to at least make a placeholder page?  (We covered the needed skills in team00).

**Review by b4k3s — DISMISSED** [review]
LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
I want to encourage you in section tomorrow to talk this through as a team.

Do you really think this design is the one that will help users figure out how to acheive their goals?

Each of the dropdowns leads only to a single menu item called search.  This doesn't really make a whole lot of sense.

I'm thinking, maybe instead:
* Course Descriptions becomes just a link instead of a dropdown, and it goes directly to the course descriptions search page.
* The other two become a single drop down called "Search by" and then the two search items under it become "Course" and "Instructor".

There could be other ways of doing it, but I think you can come up with something better than the current design, unless you really have a good rationale for why it should be these particular names leading to these particular choices.

**Review by pconrad — CHANGES_REQUESTED** [review]
Please see if you can come up with a better design that, when you show it to people that have never seen the app before, is likely to help them know what it can do for them, and where to do what.

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
